# name: CI
#
# on: push
#
# jobs:
#   test:
#     runs-on: ubuntu-latest
#
#     steps:
#       - uses: actions/checkout@v3
#       - name: Install Fish
#         run: |
#           sudo apt-add-repository -yn ppa:fish-shell/release-3
#           sudo apt-get update
#           sudo apt-get install -y fish
#
#       - name: Install Tools
#         run: |
#           source $GITHUB_WORKSPACE/functions/fisher.fish
#           fisher install $GITHUB_WORKSPACE jorgebucaran/fishtape
#           fishtape tests/*.fish
#         shell: fish {0}
